project:
  type: website
  output-dir: _site
  # resources: 
  # - shinylive-sw.js

website:  
  repo-url: https://github.com/santi-rios/China-Chemical-Dominance
  repo-actions: [edit, issue]
  title: "r-shinylive in Quarto"
  navbar:
    search: true
    left:
      - text: "Figure 1"
        file: index.qmd
  page-footer: 
  left: "Data in shinylive apps"
  right: 
    - icon: github
      href: https://github.com/coatless-tutorials/r-shinylive-data-include

lang: en

format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true

# Attach shinylive to every page
filters:
  - shinylive